version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'averox-ecommerce'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'avpass'
      MYSQL_ROOT_PASSWORD: 'avpassroot'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  # app:
  #   container_name: ecommerce-api
  #   image: 'node:10.16.3'
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     PRISMA_MANAGEMENT_API_SECRET: mysecret42
  #     PRISMA_SECRET: mysecret42
  #     PRISMA_ENDPOINT: http://prisma:4466
  #     # DEBUG: '*'
  #   depends_on:
  #     - db
  #   links:
  #     - db
  #   ports:
  #     - '8080:8080'
  #     - '5000:5000'
  #   volumes:
  #     - ./:/averox-ecommerce
  #     - /averox-ecommerce/node_modules
  #   command: 'npm run watch'
volumes:
  my-db: